version: "3"

services:
  lnbits:
    environment:
      - "TRACING=1"
    build:
        context: .
        dockerfile: Dockerfile
    image: cyphernode/lnbits
    ports: 
      - "5000:5000"
    volumes:
      - "/your/base/path/.cyphernode/lightning/testnet/lightning-rpc:/.lightning/testnet/lightning-rpc"
      - "./data:/lnbits/data"
    networks:
      - cyphernodeappsnet
    restart: always

networks:
  cyphernodeappsnet:
    external: true
